(function () {
  'use strict';
  var supportEmail = 'support@bjpack.net', reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  var qs = function (s, c) { return (c || document).querySelector(s); }, qsa = function (s, c) { return Array.prototype.slice.call((c || document).querySelectorAll(s)); };
  function categoryName(c) { return { landings: 'Landings', portfolios: 'Portfolios', stores: 'Online Stores', saas: 'SaaS' }[c] || c; }
  function initHeader() { var h = qs('#siteHeader'); if (!h) return; var update = function () { h.classList.toggle('is-scrolled', window.scrollY > 8); }; update(); window.addEventListener('scroll', update, { passive: true }); }
  function card(p, i) { var badge = p.badge ? '<span class="product-badge">' + (p.badge === 'best-seller' ? 'Best Seller' : 'New') + '</span>' : ''; var price = p.price === 0 ? 'Free' : '$' + p.price; return '<a class="product-card reveal" href="/product/' + p.id + '" data-category="' + p.category + '" style="--delay:' + (i % 6) * 45 + 'ms"><div class="product-image">' + badge + '<img src="' + p.images[0] + '" loading="lazy" alt="Preview of ' + p.title + '"></div><div class="product-info"><div><h3>' + p.title + '</h3><p>' + p.shortDescription + '</p></div><strong>' + price + '</strong></div><div class="product-meta"><span class="tag">' + categoryName(p.category) + '</span><span class="card-arrow" aria-hidden="true">↗</span></div></a>'; }
  function reveal() { var items = qsa('.reveal'); if (reducedMotion || !('IntersectionObserver' in window)) { items.forEach(function (x) { x.classList.add('is-visible'); }); return; } var io = new IntersectionObserver(function (entries, obs) { entries.forEach(function (e) { if (e.isIntersecting) { e.target.classList.add('is-visible'); obs.unobserve(e.target); } }); }, { rootMargin: '0px 0px -6% 0px', threshold: .05 }); items.forEach(function (x) { io.observe(x); }); }
  function initCatalog() { var grid = qs('#productGrid'); if (!grid || !window.products) return; grid.innerHTML = window.products.map(card).join(''); var cards = qsa('.product-card', grid), pills = qsa('.filter-pill'), count = qs('#catalogCount'); function render(filter) { var shown = 0; cards.forEach(function (c) { var visible = filter === 'all' || c.dataset.category === filter; c.classList.toggle('is-hidden', !visible); if (visible) shown++; }); count.textContent = shown + ' template' + (shown === 1 ? '' : 's'); qs('#emptyState').hidden = shown !== 0; } pills.forEach(function (pill) { pill.addEventListener('click', function () { var f = pill.dataset.filter; pills.forEach(function (x) { var on = x === pill; x.classList.toggle('is-active', on); x.setAttribute('aria-pressed', on ? 'true' : 'false'); }); render(f); }); }); render('all'); reveal(); }
  function initProduct() { var root = qs('#productPage'); if (!root || !window.products) return; var id = new URLSearchParams(window.location.search).get('id') || location.pathname.split('/').filter(Boolean).pop(), p = window.products.filter(function (x) { return x.id === id; })[0] || window.products[0]; document.title = p.title + ' — bjpack'; qs('#productTitle').textContent = p.title; qs('#productPrice').textContent = p.price === 0 ? 'Free' : '$' + p.price; qs('#productCategory').textContent = categoryName(p.category); qs('#productDescription').innerHTML = p.description; var main = qs('#productMainImage'), thumbs = qs('#productThumbs'); function show(src, alt) { main.src = src; main.alt = alt; } thumbs.innerHTML = p.images.map(function (src, i) { return '<button class="thumbnail ' + (i ? '' : 'is-active') + '" type="button" aria-label="View preview ' + (i + 1) + '"><img src="' + src + '" loading="lazy" alt=""></button>'; }).join(''); qsa('.thumbnail', thumbs).forEach(function (b, i) { b.addEventListener('click', function () { qsa('.thumbnail', thumbs).forEach(function (x) { x.classList.remove('is-active'); }); b.classList.add('is-active'); show(p.images[i], p.title + ' preview ' + (i + 1)); }); }); show(p.images[0], p.title + ' preview'); qs('#buyButton').addEventListener('click', function () { if (p.paymentUrl) { window.location.href = p.paymentUrl; return; } var link = document.createElement('a'); link.href = '/projects-code/downloads/' + p.id + '.zip'; link.download = p.id + '.zip'; document.body.appendChild(link); link.click(); link.remove(); }); }
  function initViewer() { var open = qs('#openPreview'), viewer = qs('#imageViewer'), image = qs('#viewerImage'), close = qs('#viewerClose'), source = qs('#productMainImage'); if (!open || !viewer) return; function hide() { viewer.hidden = true; viewer.classList.remove('is-tall'); document.body.style.overflow = ''; open.focus(); } open.addEventListener('click', function () { image.src = source.src; image.alt = source.alt; viewer.hidden = false; document.body.style.overflow = 'hidden'; function sizeViewer() { viewer.classList.toggle('is-tall', image.naturalHeight / image.naturalWidth > 1.65); } if (image.complete) sizeViewer(); else image.addEventListener('load', sizeViewer, { once: true }); close.focus(); }); close.addEventListener('click', hide); viewer.addEventListener('click', function (e) { if (e.target === viewer) hide(); }); document.addEventListener('keydown', function (e) { if (e.key === 'Escape' && !viewer.hidden) hide(); }); }
  function init() { initHeader(); initCatalog(); initProduct(); initViewer(); qsa('[data-support-email]').forEach(function (x) { x.textContent = supportEmail; x.href = 'mailto:' + supportEmail; }); }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init); else init();
}());
