import fs from 'node:fs/promises';
import map from '../src/lib/shortcode-map.json';
import params from '../src/lib/shortcode-params.json';
import defaults from '../src/lib/defaults.json';

async function output(file: string, contents: string) {
  if (process.argv.includes('--check')) {
    if ((await fs.readFile(file, 'utf8')) !== contents)
      throw new Error(`${file} is stale; run pnpm docs:generate`);
  } else await fs.writeFile(file, contents);
}

// Only generated reference files belong here; never overwrite authored guides.
await fs.mkdir('docs', { recursive: true });
const lines = [
  '# Component parameter index',
  '',
  '[Documentation](README.md) · [Usage and examples](components.md)',
  '',
  'Generated by `pnpm docs:generate` from local mappings; no Hugo checkout is required. Parameters summarize the migration mapping, not required fields. See the component guide for current MDX extensions.',
  '',
  '| Hugo name | MDX component | Parameter summary |',
  '| --- | --- | --- |',
];
for (const [name, component] of Object.entries(map)) {
  const names = params[name as keyof typeof params];
  lines.push(
    `| ${name} | [${component}](components.md#${component.toLowerCase()}) | ${names.length ? names.map((p) => `\`${p}\``).join(', ') : 'No mapped parameters; see usage'} |`,
  );
}
await output('docs/component-inventory.md', lines.join('\n') + '\n');

const modules: Record<string, string> = {
  site: 'Header, Base',
  nav: 'Header',
  hometop: 'HomeTop',
  aside: 'Aside',
  page: 'routes, EntryPage',
  post: 'PostCard, PostMeta, Copyright',
  theme_color: 'Base, tokens.css',
  display_mode: 'Base, main',
  font: 'Base, tokens.css',
  index_post_list: 'PostCard, astro.css',
  related_post: 'EntryPage',
  expire: 'main',
  right_menu: 'Overlays, right_menu',
  copy: 'main, utils',
  mermaid: 'Shortcode, tag-runtime',
  chart: 'Shortcode, tag-runtime',
  typeit: 'assets, tag-runtime',
  console: 'Overlays, main',
  translate: 'tw_cn',
  rightside: 'Overlays, main',
  footer: 'Footer, friend_links',
  errorpage: '404',
  capsule: 'Capsule, music',
  music: 'EntryPage, music',
  meting_api: 'assets',
  keyboard: 'keyboard',
  lazyload: 'assets, utils',
  loading: 'Base, preloader',
  highlight: 'astro.config, code-highlight',
  lightbox: 'assets, utils',
  memorial: 'Base',
  katex: 'markdown-plugin, assets',
  pwa: 'Base, manifest endpoints',
  comment: 'Comments, comments',
  twikoo: 'comments',
  waline: 'comments',
  valine: 'comments',
  artalk: 'comments',
  giscus: 'comments',
  search: 'Search, search modules',
  envelope: 'EntryPage, comments',
  brevity: 'Brevity',
  recent_comments: 'EntryPage, comments',
  verify_site: 'Base',
  extends: 'Base',
  cdn: 'assets, resources',
};
const rows = [
  '# Configuration reference',
  '',
  '[Documentation](README.md) · [Configuration guide](configuration.md) · [Development and validation](parity.md). Generated by `pnpm docs:generate` from `src/lib/defaults.json`. These are base defaults; template overrides live in `src/site.config.ts`. See the guide for top-level fields and retained compatibility settings. A field being present does not imply a visible effect in every layout.',
  '',
  '| Field | Base default | Implementation |',
  '| --- | --- | --- |',
];
function walk(value: object, keys: string[] = []) {
  for (const [k, v] of Object.entries(value)) {
    const next = [...keys, k];
    if (
      v &&
      typeof v === 'object' &&
      !Array.isArray(v) &&
      Object.keys(v).length
    )
      walk(v, next);
    else
      rows.push(
        `| \`theme.${next.join('.')}\` | \`${JSON.stringify(v).replace(/\|/g, '\\|')}\` | ${modules[next[0]] ?? 'config'} |`,
      );
  }
}
walk(defaults);
await output('docs/configuration-inventory.md', rows.join('\n') + '\n');
